version: '3.8'

services:
  database:
    container_name: clubroom-database
    image: postgres:16-alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: clubroom_dev
    ports:
      - '5432:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U postgres -d clubroom_dev']
      interval: 5s
      timeout: 3s
      retries: 10
      start_period: 10s

  backend:
    container_name: clubroom-backend
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - '5000:5000'     # Main API server
      - '5555:5555'     # Prisma Studio (optional)
    env_file:
      - .env
    environment:
      NODE_ENV: development
      DATABASE_URL: postgresql://postgres:postgres@database:5432/clubroom_dev
    depends_on:
      database:
        condition: service_healthy
    develop:
      watch:
        - action: sync
          path: ./backend/src
          target: /app/src
          ignore:
            - node_modules/
        - action: rebuild
          path: ./backend/package.json
        - action: rebuild
          path: ./backend/prisma

volumes:
  postgres_data:

networks:
  default:
    name: clubroom-network